import { useTranslation } from "react-i18next";

const vehicle_1 = "/vehicle/vehicle_11.webp";
const vehicle_12 = "/vehicle/vehicle_12.webp";
const vehicle_13 = "/vehicle/vehicle_13.webp";
const vehicle_21 = "/vehicle/vehicle_21.webp";
const vehicle_41 = "/vehicle/vehicle_41.avif";
const vehicle_51 = "/vehicle/vehicle_51.jpg";
const vehicle_61 = "/vehicle/vehicle_61.webp";
const vehicle_71 = "/vehicle/vehicle_71.jpg";
const vehicle_81 = "/vehicle/vehicle_81.avif";
const vehicle_91 = "/vehicle/vehicle_jac.jpg";
const vehicle_101 = "/vehicle/vehicle_101.webp";
const vehicle_111 = "/vehicle/vehicle_111.webp";
const vehicle_121 = "/vehicle/vehicle_121.webp";
const vehicle_131 = "/vehicle/vehicle_131.webp";
const vehicle_141 = "/vehicle/vehicle_141.jpg";
const vehicle_151 = "/vehicle/vehicle_151.jpg";
const vehicle_161 = "/vehicle/vehicle_161.jpg";
const vehicle_171 = "/vehicle/vehicle_171.jpg";
const vehicle_181 = "/vehicle/vehicle_181.avif";
const vehicle_191 = "/vehicle/vehicle_191.jpg";
const vehicle_201 = "/vehicle/vehicle_201.jpg";
const vehicle_211 = "/vehicle/vehicle_211.jpeg";
const vehicle_221 = "/vehicle/vehicle_221.jpg";
const vehicle_231 = "/vehicle/vehicle_231.jpg";
const vehicle_241 = "/vehicle/vehicle_241.jpg";
const vehicle_251 = "/vehicle/vehicle_251.jpg";

export const useTexnikaData = () => {
  const { t } = useTranslation();

  return [
    {
      id: 1,
      name: t("texnika.item1.name"),
      image: vehicle_1,
      description: t("texnika.item1.desc"),
      price: 180,
      status: "available",
      category: t("xizmatlar.menu1.filter2"),
      weight: "38 t",
      power: "224 kW",
      year: 2018,
    },
    {
      id: 2,
      name: t("texnika.item2.name"),
      image: vehicle_21,
      description: t("texnika.item2.desc"),
      price: 220,
      status: "available",
      category: t("xizmatlar.menu1.filter2"),
      weight: "48 t",
      power: "265 kW",
      year: 2017,
    },
    {
      id: 3,
      name: t("texnika.item3.name"),
      image: vehicle_1,
      description: t("texnika.item3.desc"),
      price: 260,
      status: "available",
      category: t("xizmatlar.menu1.filter2"),
      weight: "52 t",
      power: "280 kW",
      year: 2018,
    },
    {
      id: 4,
      name: t("texnika.item4.name"),
      image: vehicle_41,
      description: t("texnika.item4.desc"),
      price: 580,
      status: "available",
      category: t("xizmatlar.menu1.filter2"),
      weight: "96 t",
      power: "390 kW",
      year: 2019,
    },
    {
      id: 5,
      name: t("texnika.item5.name"),
      image: vehicle_51,
      description: t("texnika.item5.desc"),
      price: 650,
      status: "available",
      category: t("xizmatlar.menu1.filter2"),
      weight: "105 t",
      power: "420 kW",
      year: 2019,
    },
    {
      id: 6,
      name: t("texnika.item6.name"),
      image: vehicle_61,
      description: t("texnika.item6.desc"),
      price: 720,
      status: "available",
      category: t("xizmatlar.menu1.filter2"),
      weight: "120 t",
      power: "450 kW",
      year: 2013,
    },
    {
      id: 7,
      name: t("texnika.item7.name"),
      image: vehicle_71,
      description: t("texnika.item7.desc"),
      price: 130,
      status: "available",
      category: t("xizmatlar.menu1.filter3"),
      weight: "20 t",
      power: "210 kW",
      year: 2014,
    },
    {
      id: 8,
      name: t("texnika.item8.name"),
      image: vehicle_81,
      description: t("texnika.item8.desc"),
      price: 95,
      status: "available",
      category: t("xizmatlar.menu1.filter3"),
      weight: "15 t",
      power: "177 kW",
      year: 2019,
    },
    {
      id: 9,
      name: t("texnika.item9.name"),
      image: vehicle_91,
      description: t("texnika.item9.desc"),
      price: 75,
      status: "available",
      category: t("xizmatlar.menu1.filter3"),
      weight: "12 t",
      power: "158 kW",
      year: 2019,
    },
    {
      id: 10,
      name: t("texnika.item10.name"),
      image: vehicle_101,
      description: t("texnika.item10.desc"),
      price: 110,
      status: "available",
      category: t("xizmatlar.menu1.filter3"),
      weight: "18 t",
      power: "240 kW",
      year: 2019,
    },
    {
      id: 11,
      name: t("texnika.item11.name"),
      image: vehicle_111,
      description: t("texnika.item11.desc"),
      price: 310,
      status: "available",
      category: t("xizmatlar.menu1.filter4"),
      weight: "45 t",
      power: "194 kW",
      year: 2019,
    },
    {
      id: 12,
      name: t("texnika.item12.name"),
      image: vehicle_121,
      description: t("texnika.item12.desc"),
      price: 380,
      status: "available",
      category: t("xizmatlar.menu1.filter4"),
      weight: "60 t",
      power: "230 kW",
      year: 2019,
    },
    {
      id: 13,
      name: t("texnika.item13.name"),
      image: vehicle_131,
      description: t("texnika.item13.desc"),
      price: 650,
      status: "available",
      category: t("xizmatlar.menu1.filter4"),
      weight: "160 t",
      power: "410 kW",
      year: 2019,
    },
    {
      id: 14,
      name: t("texnika.item14.name"),
      image: vehicle_141,
      description: t("texnika.item14.desc"),
      price: 950,
      status: "available",
      category: t("xizmatlar.menu1.filter4"),
      weight: "90 t",
      power: "230 kW",
      year: 2017,
    },
    {
      id: 15,
      name: t("texnika.item15.name"),
      image: vehicle_151,
      description: t("texnika.item15.desc"),
      price: 580,
      status: "available",
      category: t("xizmatlar.menu1.filter4"),
      weight: "85 t",
      power: "350 kW",
      year: 2014,
    },
    {
      id: 16,
      name: t("texnika.item16.name"),
      image: vehicle_161,
      description: t("texnika.item16.desc"),
      price: 420,
      status: "available",
      category: t("xizmatlar.menu1.filter5"),
      weight: "93 t",
      power: "360 kW",
      year: 2012,
    },
    {
      id: 17,
      name: t("texnika.item17.name"),
      image: vehicle_171,
      description: t("texnika.item17.desc"),
      price: 490,
      status: "available",
      category: t("xizmatlar.menu1.filter5"),
      weight: "115 t",
      power: "390 kW",
      year: 2017,
    },
    {
      id: 18,
      name: t("texnika.item18.name"),
      image: vehicle_181,
      description: t("texnika.item18.desc"),
      price: 85,
      status: "available",
      category: t("xizmatlar.menu1.filter5"),
      weight: "8 t",
      power: "75 kW",
      year: 2009,
    },
    {
      id: 19,
      name: t("texnika.item19.name"),
      image: vehicle_191,
      description: t("texnika.item19.desc"),
      price: 60,
      status: "available",
      category: t("xizmatlar.menu1.filter6"),
      weight: "22 t",
      power: "110 kW",
      year: 1986,
    },
    {
      id: 20,
      name: t("texnika.item20.name"),
      image: vehicle_201,
      description: t("texnika.item20.desc"),
      price: 350,
      status: "available",
      category: t("xizmatlar.menu1.filter6"),
      weight: "35 t",
      power: "220 kW",
      year: 2012,
    },
    {
      id: 21,
      name: t("texnika.item21.name"),
      image: vehicle_211,
      description: t("texnika.item21.desc"),
      price: 390,
      status: "available",
      category: t("xizmatlar.menu1.filter6"),
      weight: "42 t",
      power: "260 kW",
      year: 2018,
    },
    {
      id: 22,
      name: t("texnika.item22.name"),
      image: vehicle_221,
      description: t("texnika.item22.desc"),
      price: 280,
      status: "available",
      category: t("xizmatlar.menu1.filter6"),
      weight: "30 t",
      power: "180 kW",
      year: 2018,
    },
    {
      id: 23,
      name: t("texnika.item23.name"),
      image: vehicle_231,
      description: t("texnika.item23.desc"),
      price: 460,
      status: "available",
      category: t("xizmatlar.menu1.filter5"),
      weight: "68 t",
      power: "300 kW",
      year: 2012,
    },
    {
      id: 24,
      name: t("texnika.item24.name"),
      image: vehicle_241,
      description: t("texnika.item24.desc"),
      price: 140,
      status: "available",
      category: t("xizmatlar.menu1.filter7"),
      weight: "25 t",
      power: "540 kW",
      year: 2020,
    },
    {
      id: 25,
      name: t("texnika.item25.name"),
      image: vehicle_251,
      description: t("texnika.item25.desc"),
      price: 200,
      status: "available",
      category: t("xizmatlar.menu1.filter8"),
      weight: "30 t",
      power: "—",
      year: 2018,
    },
  ];
};

export const useTexnikaSingleData = () => {
  const { t } = useTranslation();
  return [
    {
      id: 1,

      name: t("texnikaSingle.item1.name"),

      images: [vehicle_1, vehicle_12, vehicle_13],

      description: t("texnikaSingle.item1.desc"),

      price: 180,

      status: "available",

      category: "Avtokran",

      weight: "38 t",

      power: "224 kW",

      year: 2018,

      maxDepth: "—",

      maxReach: "36 m",

      bucketCapacity: "35 t",

      fuelTank: "400 L",

      features: [
        t("texnikaSingle.item1.feature1"),

        t("texnikaSingle.item1.feature2"),

        t("texnikaSingle.item1.feature3"),

        t("texnikaSingle.item1.feature4"),

        t("texnikaSingle.item1.feature5"),
      ],
    },

    {
      id: 2,

      name: t("texnikaSingle.item2.name"),

      images: [vehicle_21],

      description: t("texnikaSingle.item2.desc"),

      price: 220,

      status: "available",

      category: "Avtokran",

      weight: "48 t",

      power: "265 kW",

      year: 2017,

      maxDepth: "—",

      maxReach: "42.5 m",

      bucketCapacity: "50 t",

      fuelTank: "500 L",

      features: [
        t("texnikaSingle.item2.feature1"),

        t("texnikaSingle.item2.feature2"),

        t("texnikaSingle.item2.feature3"),

        t("texnikaSingle.item2.feature4"),

        t("texnikaSingle.item2.feature5"),
      ],
    },

    {
      id: 3,

      name: t("texnikaSingle.item3.name"),

      images: [vehicle_1, vehicle_12, vehicle_13],

      description: t("texnikaSingle.item3.desc"),

      price: 260,

      status: "available",

      category: "Avtokran",

      weight: "52 t",

      power: "280 kW",

      year: 2018,

      maxDepth: "—",

      maxReach: "43 m",

      bucketCapacity: "55 t",

      fuelTank: "520 L",

      features: [
        t("texnikaSingle.item3.feature1"),

        t("texnikaSingle.item3.feature2"),

        t("texnikaSingle.item3.feature3"),

        t("texnikaSingle.item3.feature4"),

        t("texnikaSingle.item3.feature5"),
      ],
    },
    {
      id: 4,
      name: t("texnikaSingle.item4.name"),
      images: [vehicle_41],
      description: t("texnikaSingle.item4.desc"),
      price: 580,
      status: "available",
      category: "Avtokran",
      weight: "96 t",
      power: "390 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "65 m",
      bucketCapacity: "150 t",
      fuelTank: "800 L",
      features: [
        t("texnikaSingle.item4.feature1"),
        t("texnikaSingle.item4.feature2"),
        t("texnikaSingle.item4.feature3"),
        t("texnikaSingle.item4.feature4"),
        t("texnikaSingle.item4.feature5"),
      ],
    },

    {
      id: 5,
      name: t("texnikaSingle.item5.name"),
      images: [vehicle_51],
      description: t("texnikaSingle.item5.desc"),
      price: 650,
      status: "available",
      category: "Avtokran",
      weight: "105 t",
      power: "420 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "70 m",
      bucketCapacity: "160 t",
      fuelTank: "900 L",
      features: [
        t("texnikaSingle.item5.feature1"),
        t("texnikaSingle.item5.feature2"),
        t("texnikaSingle.item5.feature3"),
        t("texnikaSingle.item5.feature4"),
        t("texnikaSingle.item5.feature5"),
      ],
    },

    {
      id: 6,
      name: t("texnikaSingle.item6.name"),
      images: [vehicle_61],
      description: t("texnikaSingle.item6.desc"),
      price: 720,
      status: "available",
      category: "Avtokran",
      weight: "120 t",
      power: "450 kW",
      year: 2013,
      maxDepth: "—",
      maxReach: "72 m",
      bucketCapacity: "180 t",
      fuelTank: "1000 L",
      features: [
        t("texnikaSingle.item6.feature1"),
        t("texnikaSingle.item6.feature2"),
        t("texnikaSingle.item6.feature3"),
        t("texnikaSingle.item6.feature4"),
        t("texnikaSingle.item6.feature5"),
      ],
    },

    {
      id: 7,
      name: t("texnikaSingle.item7.name"),
      images: [vehicle_71],
      description: t("texnikaSingle.item7.desc"),
      price: 130,
      status: "available",
      category: "Avtominora",
      weight: "20 t",
      power: "210 kW",
      year: 2014,
      maxDepth: "—",
      maxReach: "45 m",
      bucketCapacity: "—",
      fuelTank: "200 L",
      features: [
        t("texnikaSingle.item7.feature1"),
        t("texnikaSingle.item7.feature2"),
        t("texnikaSingle.item7.feature3"),
        t("texnikaSingle.item7.feature4"),
        t("texnikaSingle.item7.feature5"),
      ],
    },

    {
      id: 8,
      name: t("texnikaSingle.item8.name"),
      images: [vehicle_81],
      description: t("texnikaSingle.item8.desc"),
      price: 95,
      status: "available",
      category: "Avtominora",
      weight: "15 t",
      power: "177 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "30 m",
      bucketCapacity: "—",
      fuelTank: "160 L",
      features: [
        t("texnikaSingle.item8.feature1"),
        t("texnikaSingle.item8.feature2"),
        t("texnikaSingle.item8.feature3"),
        t("texnikaSingle.item8.feature4"),
        t("texnikaSingle.item8.feature5"),
      ],
    },

    {
      id: 9,
      name: t("texnikaSingle.item9.name"),
      images: [vehicle_91],
      description: t("texnikaSingle.item9.desc"),
      price: 75,
      status: "available",
      category: "Avtominora",
      weight: "12 t",
      power: "158 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "25 m",
      bucketCapacity: "—",
      fuelTank: "130 L",
      features: [
        t("texnikaSingle.item9.feature1"),
        t("texnikaSingle.item9.feature2"),
        t("texnikaSingle.item9.feature3"),
        t("texnikaSingle.item9.feature4"),
        t("texnikaSingle.item9.feature5"),
      ],
    },

    {
      id: 10,
      name: t("texnikaSingle.item10.name"),
      images: [vehicle_101],
      description: t("texnikaSingle.item10.desc"),
      price: 110,
      status: "available",
      category: "Avtominora",
      weight: "18 t",
      power: "240 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "38 m",
      bucketCapacity: "—",
      fuelTank: "250 L",
      features: [
        t("texnikaSingle.item10.feature1"),
        t("texnikaSingle.item10.feature2"),
        t("texnikaSingle.item10.feature3"),
        t("texnikaSingle.item10.feature4"),
        t("texnikaSingle.item10.feature5"),
      ],
    },

    {
      id: 11,
      name: t("texnikaSingle.item11.name"),
      images: [vehicle_111],
      description: t("texnikaSingle.item11.desc"),
      price: 310,
      status: "available",
      category: "Zanjirlı kran",
      weight: "45 t",
      power: "194 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "31.5 m",
      bucketCapacity: "35 t",
      fuelTank: "380 L",
      features: [
        t("texnikaSingle.item11.feature1"),
        t("texnikaSingle.item11.feature2"),
        t("texnikaSingle.item11.feature3"),
        t("texnikaSingle.item11.feature4"),
        t("texnikaSingle.item11.feature5"),
      ],
    },

    {
      id: 12,
      name: t("texnikaSingle.item12.name"),
      images: [vehicle_121],
      description: t("texnikaSingle.item12.desc"),
      price: 380,
      status: "available",
      category: "Zanjirlı kran",
      weight: "60 t",
      power: "230 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "40 m",
      bucketCapacity: "55 t",
      fuelTank: "450 L",
      features: [
        t("texnikaSingle.item12.feature1"),
        t("texnikaSingle.item12.feature2"),
        t("texnikaSingle.item12.feature3"),
        t("texnikaSingle.item12.feature4"),
        t("texnikaSingle.item12.feature5"),
      ],
    },

    {
      id: 13,
      name: t("texnikaSingle.item13.name"),
      images: [vehicle_131],
      description: t("texnikaSingle.item13.desc"),
      price: 650,
      status: "available",
      category: "Zanjirlı kran",
      weight: "160 t",
      power: "410 kW",
      year: 2019,
      maxDepth: "—",
      maxReach: "84 m",
      bucketCapacity: "135 t",
      fuelTank: "900 L",
      features: [
        t("texnikaSingle.item13.feature1"),
        t("texnikaSingle.item13.feature2"),
        t("texnikaSingle.item13.feature3"),
        t("texnikaSingle.item13.feature4"),
        t("texnikaSingle.item13.feature5"),
      ],
    },

    {
      id: 14,
      name: t("texnikaSingle.item14.name"),
      images: [vehicle_141],
      description: t("texnikaSingle.item14.desc"),
      price: 950,
      status: "available",
      category: "Zanjirlı kran",
      weight: "90 t",
      power: "230 kW",
      year: 2017,
      maxDepth: "—",
      maxReach: "88 m",
      bucketCapacity: "220 t",
      fuelTank: "700 L",
      features: [
        t("texnikaSingle.item14.feature1"),
        t("texnikaSingle.item14.feature2"),
        t("texnikaSingle.item14.feature3"),
        t("texnikaSingle.item14.feature4"),
        t("texnikaSingle.item14.feature5"),
      ],
    },

    {
      id: 15,
      name: t("texnikaSingle.item15.name"),
      images: [vehicle_151],
      description: t("texnikaSingle.item15.desc"),
      price: 580,
      status: "available",
      category: "Zanjirlı kran",
      weight: "85 t",
      power: "350 kW",
      year: 2014,
      maxDepth: "—",
      maxReach: "60 m",
      bucketCapacity: "85 t",
      fuelTank: "700 L",
      features: [
        t("texnikaSingle.item15.feature1"),
        t("texnikaSingle.item15.feature2"),
        t("texnikaSingle.item15.feature3"),
        t("texnikaSingle.item15.feature4"),
        t("texnikaSingle.item15.feature5"),
      ],
    },
    {
      id: 16,
      name: "Bauer BG 36",
      images: [vehicle_161],
      description:
        "Bauer BG 36 — rotatsion Burg'ilovchi texnika qurilma. Kelly burg'ulash, tuproqni aralashtirish va zamin mustahkamlash uchun ko'p funksiyali qurilma. 360 kNm maksimal burovchi kuch bilan qattiq va murakkab gruntlarda ishlay oladi.",
      price: 420,
      status: "available",
      category: "Burg'ilovchi texnika",
      weight: "93 t",
      power: "360 kW",
      year: 2012,
      maxDepth: "36 m",
      maxReach: "—",
      bucketCapacity: "2.5 m³",
      fuelTank: "600 L",
      features: [
        "360 kNm maksimal burovchi kuch",
        "Kelly burg'ulash va CFA tizimi",
        "Tuproqni aralashtirish (SMW)",
        "B-Tronic raqamli boshqaruv",
        "Zanjirlı yurish tizimi",
      ],
    },
    {
      id: 16,
      name: t("texnikaSingle.item16.name"),
      images: [vehicle_161],
      description: t("texnikaSingle.item16.desc"),
      price: 420,
      status: "available",
      category: "Burg'ilovchi texnika",
      weight: "93 t",
      power: "360 kW",
      year: 2012,
      maxDepth: "36 m",
      maxReach: "—",
      bucketCapacity: "2.5 m³",
      fuelTank: "600 L",
      features: [
        t("texnikaSingle.item16.feature1"),
        t("texnikaSingle.item16.feature2"),
        t("texnikaSingle.item16.feature3"),
        t("texnikaSingle.item16.feature4"),
        t("texnikaSingle.item16.feature5"),
      ],
    },

    {
      id: 17,
      name: t("texnikaSingle.item17.name"),
      images: [vehicle_171],
      description: t("texnikaSingle.item17.desc"),
      price: 490,
      status: "available",
      category: "Burg'ilovchi texnika",
      weight: "115 t",
      power: "390 kW",
      year: 2017,
      maxDepth: "88 m",
      maxReach: "—",
      bucketCapacity: "3.0 m",
      fuelTank: "700 L",
      features: [
        t("texnikaSingle.item17.feature1"),
        t("texnikaSingle.item17.feature2"),
        t("texnikaSingle.item17.feature3"),
        t("texnikaSingle.item17.feature4"),
        t("texnikaSingle.item17.feature5"),
      ],
    },

    {
      id: 18,
      name: t("texnikaSingle.item18.name"),
      images: [vehicle_181],
      description: t("texnikaSingle.item18.desc"),
      price: 85,
      status: "available",
      category: "Burg'ilovchi texnika",
      weight: "8 t",
      power: "75 kW",
      year: 2009,
      maxDepth: "10 m",
      maxReach: "—",
      bucketCapacity: "200 mm",
      fuelTank: "80 L",
      features: [
        t("texnikaSingle.item18.feature1"),
        t("texnikaSingle.item18.feature2"),
        t("texnikaSingle.item18.feature3"),
        t("texnikaSingle.item18.feature4"),
        t("texnikaSingle.item18.feature5"),
      ],
    },

    {
      id: 19,
      name: t("texnikaSingle.item19.name"),
      images: [vehicle_191],
      description: t("texnikaSingle.item19.desc"),
      price: 60,
      status: "available",
      category: "Qoziq qoqadigan texnika",
      weight: "22 t",
      power: "110 kW",
      year: 1986,
      maxDepth: "20 m",
      maxReach: "—",
      bucketCapacity: "5 t",
      fuelTank: "150 L",
      features: [
        t("texnikaSingle.item19.feature1"),
        t("texnikaSingle.item19.feature2"),
        t("texnikaSingle.item19.feature3"),
        t("texnikaSingle.item19.feature4"),
        t("texnikaSingle.item19.feature5"),
      ],
    },

    {
      id: 20,
      name: t("texnikaSingle.item20.name"),
      images: [vehicle_201],
      description: t("texnikaSingle.item20.desc"),
      price: 350,
      status: "available",
      category: "Qoziq qoqadigan texnika",
      weight: "35 t",
      power: "220 kW",
      year: 2012,
      maxDepth: "25 m",
      maxReach: "—",
      bucketCapacity: "50 t",
      fuelTank: "350 L",
      features: [
        t("texnikaSingle.item20.feature1"),
        t("texnikaSingle.item20.feature2"),
        t("texnikaSingle.item20.feature3"),
        t("texnikaSingle.item20.feature4"),
        t("texnikaSingle.item20.feature5"),
      ],
    },

    {
      id: 21,
      name: t("texnikaSingle.item21.name"),
      images: [vehicle_211],
      description: t("texnikaSingle.item21.desc"),
      price: 390,
      status: "available",
      category: "Qoziq qoqadigan texnika",
      weight: "42 t",
      power: "260 kW",
      year: 2018,
      maxDepth: "30 m",
      maxReach: "—",
      bucketCapacity: "100 t",
      fuelTank: "400 L",
      features: [
        t("texnikaSingle.item21.feature1"),
        t("texnikaSingle.item21.feature2"),
        t("texnikaSingle.item21.feature3"),
        t("texnikaSingle.item21.feature4"),
        t("texnikaSingle.item21.feature5"),
      ],
    },

    {
      id: 22,
      name: t("texnikaSingle.item22.name"),
      images: [vehicle_221],
      description: t("texnikaSingle.item22.desc"),
      price: 280,
      status: "available",
      category: "Qoziq qoqadigan texnika",
      weight: "30 t",
      power: "180 kW",
      year: 2018,
      maxDepth: "22 m",
      maxReach: "—",
      bucketCapacity: "20 t",
      fuelTank: "300 L",
      features: [
        t("texnikaSingle.item22.feature1"),
        t("texnikaSingle.item22.feature2"),
        t("texnikaSingle.item22.feature3"),
        t("texnikaSingle.item22.feature4"),
        t("texnikaSingle.item22.feature5"),
      ],
    },

    {
      id: 23,
      name: t("texnikaSingle.item23.name"),
      images: [vehicle_231],
      description: t("texnikaSingle.item23.desc"),
      price: 460,
      status: "available",
      category: "Burg'ilovchi texnika",
      weight: "68 t",
      power: "300 kW",
      year: 2012,
      maxDepth: "50 m",
      maxReach: "—",
      bucketCapacity: "3.0 m",
      fuelTank: "600 L",
      features: [
        t("texnikaSingle.item23.feature1"),
        t("texnikaSingle.item23.feature2"),
        t("texnikaSingle.item23.feature3"),
        t("texnikaSingle.item23.feature4"),
        t("texnikaSingle.item23.feature5"),
      ],
    },

    {
      id: 24,
      name: t("texnikaSingle.item24.name"),
      images: [vehicle_241],
      description: t("texnikaSingle.item24.desc"),
      price: 140,
      status: "available",
      category: "Tyagach",
      weight: "25 t",
      power: "540 kW",
      year: 2020,
      maxDepth: "—",
      maxReach: "—",
      bucketCapacity: "500 t",
      fuelTank: "900 L",
      features: [
        t("texnikaSingle.item24.feature1"),
        t("texnikaSingle.item24.feature2"),
        t("texnikaSingle.item24.feature3"),
        t("texnikaSingle.item24.feature4"),
        t("texnikaSingle.item24.feature5"),
      ],
    },

    {
      id: 25,
      name: t("texnikaSingle.item25.name"),
      images: [vehicle_251],
      description: t("texnikaSingle.item25.desc"),
      price: 200,
      status: "available",
      category: "Tirkama",
      weight: "30 t",
      power: "—",
      year: 2018,
      maxDepth: "—",
      maxReach: "—",
      bucketCapacity: "360 t",
      fuelTank: "—",
      features: [
        t("texnikaSingle.item25.feature1"),
        t("texnikaSingle.item25.feature2"),
        t("texnikaSingle.item25.feature3"),
        t("texnikaSingle.item25.feature4"),
        t("texnikaSingle.item25.feature5"),
      ],
    },
  ];
};
