const lang = localStorage.getItem("i18nextLng");

const alphaLatin = [
  //lotin-kirill uchun lotin alfaviti
  "A",
  "B",
  "V",
  "G",
  "D",
  "E",
  "‡",
  "J",
  "Z",
  "I",
  "Y",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "R",
  "S",
  "T",
  "U",
  "F",
  "X",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "Q",
  "H",
  "‡",
  "a",
  "b",
  "v",
  "g",
  "d",
  "e",
  "‡",
  "j",
  "z",
  "i",
  "y",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "r",
  "s",
  "t",
  "u",
  "f",
  "x",
  "‡",
  "‡",
  "‡",
  "‡",
  "'",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "‡",
  "q",
  "h",
  "‡",
];
const alphaRus = [
  "А",
  "Б",
  "В",
  "Г",
  "Д",
  "Е",
  "Ё",
  "Ж",
  "З",
  "И",
  "Й",
  "К",
  "Л",
  "М",
  "Н",
  "О",
  "П",
  "Р",
  "С",
  "Т",
  "У",
  "Ф",
  "Х",
  "Ц",
  "Ч",
  "Ш",
  "Щ",
  "Ъ",
  "Ы",
  "Ь",
  "Э",
  "Ю",
  "Я",
  "Ғ",
  "Қ",
  "Ҳ",
  "Ў",
  "а",
  "б",
  "в",
  "г",
  "д",
  "е",
  "ё",
  "ж",
  "з",
  "и",
  "й",
  "к",
  "л",
  "м",
  "н",
  "о",
  "п",
  "р",
  "с",
  "т",
  "у",
  "ф",
  "х",
  "ц",
  "ч",
  "ш",
  "щ",
  "ъ",
  "ы",
  "ь",
  "э",
  "ю",
  "я",
  "ғ",
  "қ",
  "ҳ",
  "ў",
];
const qisqartmamap = {
  "'": "&apos;",
  "<": "&lt;",
  ">": "&gt;",
  " ": "&nbsp;",
  "¡": "&iexcl;",
  "¢": "&cent;",
  "£": "&pound;",
  "¤": "&curren;",
  "¥": "&yen;",
  "¦": "&brvbar;",
  "§": "&sect;",
  "¨": "&uml;",
  "©": "&copy;",
  ª: "&ordf;",
  "«": "&laquo;",
  "¬": "&not;",
  "®": "&reg;",
  "¯": "&macr;",
  "°": "&deg;",
  "±": "&plusmn;",
  "²": "&sup2;",
  "³": "&sup3;",
  "´": "&acute;",
  µ: "&micro;",
  "¶": "&para;",
  "·": "&middot;",
  "¸": "&cedil;",
  "¹": "&sup1;",
  º: "&ordm;",
  "»": "&raquo;",
  "¼": "&frac14;",
  "½": "&frac12;",
  "¾": "&frac34;",
  "¿": "&iquest;",
  À: "&Agrave;",
  Á: "&Aacute;",
  Â: "&Acirc;",
  Ã: "&Atilde;",
  Ä: "&Auml;",
  Å: "&Aring;",
  Æ: "&AElig;",
  Ç: "&Ccedil;",
  È: "&Egrave;",
  É: "&Eacute;",
  Ê: "&Ecirc;",
  Ë: "&Euml;",
  Ì: "&Igrave;",
  Í: "&Iacute;",
  Î: "&Icirc;",
  Ï: "&Iuml;",
  Ð: "&ETH;",
  Ñ: "&Ntilde;",
  Ò: "&Ograve;",
  Ó: "&Oacute;",
  Ô: "&Ocirc;",
  Õ: "&Otilde;",
  Ö: "&Ouml;",
  "×": "&times;",
  Ø: "&Oslash;",
  Ù: "&Ugrave;",
  Ú: "&Uacute;",
  Û: "&Ucirc;",
  Ü: "&Uuml;",
  Ý: "&Yacute;",
  Þ: "&THORN;",
  ß: "&szlig;",
  à: "&agrave;",
  á: "&aacute;",
  â: "&acirc;",
  ã: "&atilde;",
  ä: "&auml;",
  å: "&aring;",
  æ: "&aelig;",
  ç: "&ccedil;",
  è: "&egrave;",
  é: "&eacute;",
  ê: "&ecirc;",
  ë: "&euml;",
  ì: "&igrave;",
  í: "&iacute;",
  î: "&icirc;",
  ï: "&iuml;",
  ð: "&eth;",
  ñ: "&ntilde;",
  ò: "&ograve;",
  ó: "&oacute;",
  ô: "&ocirc;",
  õ: "&otilde;",
  ö: "&ouml;",
  "÷": "&divide;",
  ø: "&oslash;",
  ù: "&ugrave;",
  ú: "&uacute;",
  û: "&ucirc;",
  ü: "&uuml;",
  ý: "&yacute;",
  þ: "&thorn;",
  ÿ: "&yuml;",
  Œ: "&OElig;",
  œ: "&oelig;",
  Š: "&Scaron;",
  š: "&scaron;",
  Ÿ: "&Yuml;",
  ƒ: "&fnof;",
  ˆ: "&circ;",
  "˜": "&tilde;",
  Α: "&Alpha;",
  Β: "&Beta;",
  Γ: "&Gamma;",
  Δ: "&Delta;",
  Ε: "&Epsilon;",
  Ζ: "&Zeta;",
  Η: "&Eta;",
  Θ: "&Theta;",
  Ι: "&Iota;",
  Κ: "&Kappa;",
  Λ: "&Lambda;",
  Μ: "&Mu;",
  Ν: "&Nu;",
  Ξ: "&Xi;",
  Ο: "&Omicron;",
  Π: "&Pi;",
  Ρ: "&Rho;",
  Σ: "&Sigma;",
  Τ: "&Tau;",
  Υ: "&Upsilon;",
  Φ: "&Phi;",
  Χ: "&Chi;",
  Ψ: "&Psi;",
  Ω: "&Omega;",
  α: "&alpha;",
  β: "&beta;",
  γ: "&gamma;",
  δ: "&delta;",
  ε: "&epsilon;",
  ζ: "&zeta;",
  η: "&eta;",
  θ: "&theta;",
  ι: "&iota;",
  κ: "&kappa;",
  λ: "&lambda;",
  μ: "&mu;",
  ν: "&nu;",
  ξ: "&xi;",
  ο: "&omicron;",
  π: "&pi;",
  ρ: "&rho;",
  ς: "&sigmaf;",
  σ: "&sigma;",
  τ: "&tau;",
  υ: "&upsilon;",
  φ: "&phi;",
  χ: "&chi;",
  ψ: "&psi;",
  ω: "&omega;",
  ϑ: "&thetasym;",
  ϒ: "&Upsih;",
  ϖ: "&piv;",
  "–": "&ndash;",
  "—": "&mdash;",
  "‘": "&lsquo;",
  "’": "&rsquo;",
  "‚": "&sbquo;",
  "“": "&ldquo;",
  "”": "&rdquo;",
  "„": "&bdquo;",
  "†": "&dagger;",
  "‡": "&Dagger;",
  "•": "&bull;",
  "…": "&hellip;",
  "‰": "&permil;",
  "′": "&prime;",
  "″": "&Prime;",
  "‹": "&lsaquo;",
  "›": "&rsaquo;",
  "‾": "&oline;",
  "⁄": "&frasl;",
  "€": "&euro;",
  ℑ: "&image;",
  "℘": "&weierp;",
  ℜ: "&real;",
  "™": "&trade;",
  ℵ: "&alefsym;",
  "←": "&larr;",
  "↑": "&uarr;",
  "→": "&rarr;",
  "↓": "&darr;",
  "↔": "&harr;",
  "↵": "&crarr;",
  "⇐": "&lArr;",
  "⇑": "&UArr;",
  "⇒": "&rArr;",
  "⇓": "&dArr;",
  "⇔": "&hArr;",
  "∀": "&forall;",
  "∂": "&part;",
  "∃": "&exist;",
  "∅": "&empty;",
  "∇": "&nabla;",
  "∈": "&isin;",
  "∉": "&notin;",
  "∋": "&ni;",
  "∏": "&prod;",
  "∑": "&sum;",
  "−": "&minus;",
  "∗": "&lowast;",
  "√": "&radic;",
  "∝": "&prop;",
  "∞": "&infin;",
  "∠": "&ang;",
  "∧": "&and;",
  "∨": "&or;",
  "∩": "&cap;",
  "∪": "&cup;",
  "∫": "&int;",
  "∴": "&there4;",
  "∼": "&sim;",
  "≅": "&cong;",
  "≈": "&asymp;",
  "≠": "&ne;",
  "≡": "&equiv;",
  "≤": "&le;",
  "≥": "&ge;",
  "⊂": "&sub;",
  "⊃": "&sup;",
  "⊄": "&nsub;",
  "⊆": "&sube;",
  "⊇": "&supe;",
  "⊕": "&oplus;",
  "⊗": "&otimes;",
  "⊥": "&perp;",
  "⋅": "&sdot;",
  "⌈": "&lceil;",
  "⌉": "&rceil;",
  "⌊": "&lfloor;",
  "⌋": "&rfloor;",
  "⟨": "&lang;",
  "⟩": "&rang;",
  "◊": "&loz;",
  "♠": "&spades;",
  "♣": "&clubs;",
  "♥": "&hearts;",
  "♦": "&diams;",
};

export function transliterate(word) {
  let text = false;
  if (word && lang === "УЗ") {
    for (const [key, value] of Object.entries(qisqartmamap)) {
      let str1 = value;
      let re = new RegExp(str1, "g");
      word = word.replace(re, `${key}`);
    }
    // console.log(word);
    word = word.replace(/`/g, "'");
    word = word.replace(/ʹ/g, "'");
    word = word.replace(/ʻ/g, "'");
    word = word.replace(/ʼ/g, "'");
    word = word.replace(/ʽ/g, "'");
    word = word.replace(/ˊ/g, "'");
    word = word.replace(/ˋ/g, "'");
    word = word.replace(/‘/g, "'");
    word = word.replace(/Ye/g, "Е");
    word = word.replace(/YE/g, "Е");
    word = word.replace(/Yo/g, "Ё");
    word = word.replace(/YO/g, "Ё");
    word = word.replace(/Ch/g, "Ч");
    word = word.replace(/CH/g, "Ч");
    word = word.replace(/Sh/g, "Ш");
    word = word.replace(/SH/g, "Ш");
    word = word.replace(/Yu/g, "Ю");
    word = word.replace(/YU/g, "Ю");
    word = word.replace(/Ya/g, "Я");
    word = word.replace(/YA/g, "Я");
    word = word.replace(/Ts/g, "Ц");
    word = word.replace(/TS/g, "Ц");
    word = word.replace(/G\'/g, "Ғ");
    word = word.replace(/O\'/g, "Ў");
    word = word.replace(/ye/g, "е");
    word = word.replace(/yo/g, "ё");
    word = word.replace(/ch/g, "ч");
    word = word.replace(/sh/g, "ш");
    word = word.replace(/yu/g, "ю");
    word = word.replace(/ya/g, "я");
    word = word.replace(/ts/g, "ц");
    word = word.replace(/g'/g, "ғ");
    word = word.replace(/o'/g, "ў");
    return word
      .split("")
      .map(function (char) {
        if (char == "<") {
          text = true;
          return char;
        } else if (char == ">") {
          text = false;
          return char;
        } else if (text == true) {
          return char;
        } else {
          if (alphaLatin?.indexOf(char) > -1) {
            return alphaRus?.[alphaLatin?.indexOf(char)];
          } else return char;
        }
      })
      .join("");
  } else return word;
}
